### ISSUE TITLE
Actions API: define the life cycle of action and clarify the role of action class.

### ISSUE THREAD

**Issue by sogaani** [mozilla-iot/gateway-addon-node#12]
Since the current API is a little bit free for implementation of actions, there are many things to consider such as control of action lifecycle and asynchronous processing at development time.
As a developer, it is better to implement methods which is empty now on the device base class and reduce the methods that the developer should implement.

I'm implementing an action with my [add-on](https://github.com/sogaani/broadlink-adapter).
 [This](https://github.com/sogaani/broadlink-adapter/blob/master/ir-device.js) is my implementation of the device class and developer maybe can handle various actions by implementing the following method.
* device.createAction
* action.perform
* action.cancel

**Comment by sogaani** [comment]
@mrstegeman Yes, I feel more reasonable than add-on, because we can focus to implement ```performAction``` and ```cancel``` methods.
In addon, I think that start and cancel should be called automatically.

**Comment by mrstegeman** [comment]
@sogaani There was a specific reason that `start` was not called automatically for the webthing library, but it could probably be automatic for this library.
