### ISSUE TITLE
Access Gateway from ApiHandler

### ISSUE THREAD

**Issue by Kozloff** [mozilla-iot/gateway-addon-node#57]
Hi @mrstegeman! Recently I asked you a few questions https://github.com/mozilla-iot/gateway/issues/2248. Now I'm stuck on accessing the gateway in ApiHandler. I understand that I have to do this through the PluginManager or AddonManagerProxy, but I don’t understand how to access it. Сan you help me with this (sample code with access to the list of devices)?

P.S. You will save a lot of my time
P.P.S. I can program only with Googling =)
P.P.P.S gateway wiki is outdated (https://github.com/mozilla-iot/wiki/wiki)
```
'use strict';

const {APIHandler, APIResponse, Adapter} = require('gateway-addon');
...

class DialogsAPIHandler extends APIHandler {
  constructor(addonManager) {
    super(addonManager, manifest.id);
    addonManager.addAPIHandler(this);
  }

  async handleRequest(request) {
    console.info(JSON.stringify(request))
    var baseResponse = ...
    if (request.method === 'HEAD' && request.path === '/v1.0/') {
      new APIResponse({
        status: 200
      });
    } else if (request.method === 'POST' ...) {
     ...
    } else if (request.method === 'GET' && request.path === '/v1.0/user/devices') {

      // Here I need to work with the gateway through some kind of internal mechanism
     var gatewayDevices = this.<something>.getDevices();
      

      return new APIResponse({
        status: 200,
        contentType: 'application/json',
        content: JSON.stringify(baseResponse),
      });
    } else {
      return new APIResponse({
        status: 404
      });
    }
  }
}
module.exports = DialogsAPIHandler;
```

**Comment by mrstegeman** [comment]
You can't do what you're asking to do directly. The add-on runs in a completely separate process from the gateway, so you cannot directly access gateway interfaces. What you could do instead is one of the following:

1. Start using the `handleDeviceSaved()` method of the Adapter class. You could create an Adapter and attach it to the APIHandler.
2. Use the [REST API](https://iot.mozilla.org/wot/#web-thing-rest-api) to talk to the gateway.

Also, yes, the wiki is horribly outdated. We're working on updating and centralizing our documentation.

**Comment by Kozloff** [comment]
Thank a lot
