### ISSUE TITLE
handleDeviceSaved() / removeThing() pair, not fully reliable

### ISSUE THREAD

**Issue by adioanca-rpma** [mozilla-iot/gateway-addon-node#64]
using version 0.12

as per `handleDeviceSaved()` documentation:

>    ```
>    * This can be used for keeping track of what devices have previously been
>    * discovered, such that the adapter can rebuild those, clean up old nodes,
>    * etc.
>    ```

I wanted to use these functions to keep track of user saved devices VS all devices provided by the addon.
If a device is connected (a Device object exists and is present in `addon-manager.js`s `this.device` map) then an adapter's `removeThing(deviceObj)` is called.
If a device is disconnected (its ex Device object was deleted from `addon-manager.js`s `this.device` map) then AddonManager's `removeThing(deviceId)` does not find a valid `device` object and and addon's `removeThing(deviceObj)` is, of course, not called anymore.

So, if a developer wants to push a device ID in `handleDeviceSaved()` into an array, and then use `removeThing()` to pop that device ID from that array - to keep track of the devices added/removed by the user from the UI/API, it will not work reliably.

Have I misunderstood how to use these functions?
How can I detect in my addon when a disconnected device is removed by the user from the UI/API?

**Comment by mrstegeman** [comment]
When an add-on first starts, the `handleDeviceSaved()` callback will be called with every single device that has already been saved by the user. If the user saves a new device while the add-on is running, the same callback will be called again with the new device. This callback is called in every adapter, for every device, regardless of whether or not the devices belongs to that adapter.

`removeThing()`, on the other hand, is only called in the specific adapter that owns the device. It is called when the user removes the device via the UI/API. `removeThing()`, in turn, calls `handleDeviceRemoved()`, which actually removes it from the adapter instance's `this.devices` map.

Device instances initially make it into `this.devices` when `handleDeviceAdded()` is called.

Does that clear things up at all?

**Comment by adioanca-rpma** [comment]
Hi Michael,

> When an add-on first starts, the `handleDeviceSaved()` callback will be called with every single device that has already been saved by the user. If the user saves a new device while the add-on is running, the same callback will be called again with the new device. This callback is called in every adapter, for every device, regardless of whether or not the devices belongs to that adapter.

Yup, using `handleDeviceSaved()` is a good way to track what devices have been saved by the user.
With the existence of `handleDeviceSaved()` - which announces an adapter that one of its devices is saved, I would have expected that a counterpart function (e.g. `handleDeviceUnSaved()` or `handleDeviceDeleted()`) existed too - to let the adapter know that one of its devices has been deleted from the UI/API.
But I could not find such an adapter function. The closest that I've found was `removeThing()` which is called in a single place - inside `AddonManager.removeThing()` which in turn is called from `ThingsController.delete('/:thingId'...`. Since this `HTTP DELETE`(user deleted a device) path directly goes to an addon's `Adapter.removeThing()` and there's no other callback (towards the addon) beside `handleDeviceSaved()` to announce that a device has been saved by the user, I must conclude that `handleDeviceSaved()` and `removeThing()` are a pair.

Please correct me if my judgement is wrong.

Now, if a device is online (a Device object exists), and it present in the UI, addon's Adapter.removeThing() is called. This is the behaviour that I've expected, and it's working great.
But, it a device is disconnected (addon Adapter implementation removed the Device object - the practice that I've observed in all examples and other addons), `removeThing()` is not called anymore. I would have expected that it'd be called.

You may ask why I needed this? Well, I wanted to keep track of all the devices (their IDs only) that our addon has seen, and create new Device objects for them only during `startPairing(timeoutSeconds)` - after pairing would timeout, I would have removed Device objects that were not saved in the UI.

Since this `handleDeviceSaved()` and `removeThing()` pair didn't worked for offline devices, the workaround was to create new Device objects for every device that ours addon detected over the network.

So I got this solved in another way, but it is still my opinion that `removeThing()` should be called in addon's Adapter, even if the device is disconnected.


:) Sorry for the long reply.

Regards,
Adi.

**Comment by mrstegeman** [comment]
Just to clarify, are you wanting to know when _any_ device is removed/unsaved, or just those from your specific add-on?

**Comment by adioanca-rpma** [comment]
Just those specific to an addon. Created/Associated by/with it.

**Comment by mrstegeman** [comment]
I guess I'm confused. You're suggesting a situation like this, unless I'm mistaken:

1. Adapter creates device X
2. User saves device X
3. Gateway/add-on restarts, or something
4. Adapter sees device X in `handleDeviceSaved`, but the adapter has not (and does not) created that device again
5. User deletes device
6. `removeThing` is not called in the adapter

Am I understanding that right?

**Comment by adioanca-rpma** [comment]
Yes. I think I can agree with those 6 points.

The exact situation:
1. Adapter creates device X
2. User saves device X
3. Device X becomes disconnected (Device object removed by Adapter)
4. User deletes device
5. removeThing is not called in the adapter

... if step 3. is not made, then:
1. Adapter creates device X
2. User saves device X
3. User deletes device
4. removeThing IS called in the adapter

**Comment by mrstegeman** [comment]
Ok, now we're getting somewhere.

To directly answer your question, no, there is not a `handleDeviceUnsaved` callback to pair with `handleDeviceSaved`.

The better answer here, though, is that you should be using [`connectedNotify`](https://github.com/mozilla-iot/gateway-addon-node/blob/master/lib/device.js#L190-L192), rather than removing the device from your adapter when it becomes disconnected. Then, you'll still receive the call to `removeThing`.

**Comment by adioanca-rpma** [comment]
> To directly answer your question, no, there is not a `handleDeviceUnsaved` callback to pair with `handleDeviceSaved`.

I have a (not yet well thought) proposal about this. more on this below.

> The better answer here, though, is that you should be using [`connectedNotify`](https://github.com/mozilla-iot/gateway-addon-node/blob/master/lib/device.js#L190-L192), rather than removing the device from your adapter when it becomes disconnected. Then, you'll still receive the call to `removeThing`.

I don't think this will work either.
Take this situation:
1. Adapter creates device X
2. User saves device X
3. User restarts Gateway or addon
3.1. No Device object is created by the addon, because device X has a heartbeat at 5m
4. User deletes device X
5. removeThing is not called.

Another situation:
1. Adapter creates device X
2. User saves device X
3. User restarts Gateway or addon
3.1. addon has saved device X ID in its DB config, and creates a new Device object and immediately calls connectedNotify(false) ... 5m pass, heartbeat is received, connectedNotify(true) is called.
4. User deletes device X
5. removeThing is called (I trust you, I haven't tested).
This would in result in a flicker device connected/disconnected in the UI, but more importantly (IIRC) a connected/disconnected in clients using the Gateway WebSockets API.

Maybe I'm wrong with the situations presented above, I'll have to test.


Moving on, I mentioned I have a proposal. Maybe it's far too far fetched, but then again the current version is 0.12 so I guess the API is subject to changes.
In `adapter.js` this is the list of functions that have a mandatory `device` object as parameter:
```javascript
removeThing(device)
cancelRemoveThing(device)

handleDeviceAdded(device)
handleDeviceRemoved(device)
```
While `handleDeviceAdded` and `handleDeviceRemoved` must have a `device` object as a parameter because these must be called by the addon developer to add and remove devices, the other two are callbacks and in my opinion these should have a `thingId`/`deviceId` as parameter - just like the other methods of Adapter class.
Then, their implementation would look like:
```
  removeThing(deviceId) {
    const device = this.getDevice(deviceId);
    if (device) {
      console.log('Adapter:', this.name, 'id', this.id,
                'removeThing(', device.id, ') started');
      this.handleDeviceRemoved(device);
    }
  }

  cancelRemoveThing(deviceId) {
    console.log('Adapter:', this.name, 'id', this.id,
                'cancelRemoveThing(', deviceId, ')');
  }
```
This would pave the way for `removeThing` being called then the user removes a disconnected(i.e. no Device object) device from the UI. (probably other changes are required too, like in AddonManager's `removeThing`..?)

Just my 2c. I'm a beginner with WebThings GW code...

**Comment by mrstegeman** [comment]
> Take this situation:
> 1. Adapter creates device X
> 2. User saves device X
> 3. User restarts Gateway or addon
>     3.1. No Device object is created by the addon, because device X has a heartbeat at 5m
> 4. User deletes device X
> 5. removeThing is not called.

This is precisely why `handleDeviceSaved` was initially added to the API. It was added for adapters which could not always reliably use a discovery mechanism to re-add devices. So, instead, you can use the `handleDeviceSaved` callback to rebuild the devices internally, without needing to wait for that heartbeat.

> Another situation:
> 1. Adapter creates device X
> 2. User saves device X 
> 3. User restarts Gateway or addon
>     3.1. addon has saved device X ID in its DB config, and creates a new Device object and immediately calls connectedNotify(false) ... 5m pass, heartbeat is received, connectedNotify(true) is called.
> 4. User deletes device X 
> 5. removeThing is called (I trust you, I haven't tested).
>   This would result in a flicker device connected/disconnected in the UI, but more importantly (IIRC) a connected/disconnected in clients using the Gateway WebSockets API.

There is a `thingRemoved` message that gets sent across the WebSocket to notify the client that the device has been removed.

> Moving on, I mentioned I have a proposal. Maybe it's too far fetched, but then again the current version is 0.12 so I guess the API is subject to changes.
> In `adapter.js` this is the list of functions that have a mandatory `device` object as parameter:
> 
> ```js
> removeThing(device)
> cancelRemoveThing(device)
> 
> handleDeviceAdded(device)
> handleDeviceRemoved(device)
> ```
> 
> While `handleDeviceAdded` and `handleDeviceRemoved` must have a `device` object as a parameter because these must be called by the addon developer to add and remove devices, the other two are callbacks and in my opinion these should have a `thingId`/`deviceId` as parameter - just like the other methods of Adapter class.
> Then, their implementation would look like:
> 
> ```
>   removeThing(deviceId) {
>     const device = this.getDevice(deviceId);
>     if (device) {
>       console.log('Adapter:', this.name, 'id', this.id,
>                 'removeThing(', device.id, ') started');
>       this.handleDeviceRemoved(device);
>     }
>   }
> 
>   cancelRemoveThing(deviceId) {
>     console.log('Adapter:', this.name, 'id', this.id,
>                 'cancelRemoveThing(', deviceId, ')');
>   }
> ```
> 
> This would pave the way for `removeThing` being called then the user removes a disconnected(i.e. no Device object) device from the UI. (probably other changes are required too, like in AddonManager's `removeThing`..?)

This actually wouldn't change anything at all, and would end up breaking all existing add-ons. The device ID is already available in that callback, as `device.id`. The gateway has the entire thing model cached. The problem is that it's not presently attached to any adapter, so the callback is never called inside the adapter that originally created it.

**Comment by adioanca-rpma** [comment]
Okay... then, so be it.
From my PoV these are some API inconsistencies, but I've managed to implement the functionality I needed by using other functions, so we can close this issue.

Thank you for your time Michael.
