### ISSUE TITLE
Cannot trigger event with 'false' payload

### ISSUE THREAD

**Issue by adioanca-rpma** [mozilla-iot/gateway-addon-node#65]
[This](https://github.com/mozilla-iot/gateway-addon-node/blob/master/lib/event.js#L27) line needs to be changed to(or similar):
```javascript
this.data = (data === 'undefined' || data === NaN)? null: data;
```

Unfortunately this is not enough, and the GW code [here](https://github.com/mozilla-iot/gateway/blob/master/src/models/event.js#L25) needs to be changed too.

**Comment by mrstegeman** [comment]
Great find!
