### ISSUE TITLE
How to cleanup resources allocated in subclassed Device objects?

### ISSUE THREAD

**Issue by adioanca-rpma** [mozilla-iot/gateway-addon-node#66]
Hi,

I have the following setup:
```javascript
class MyDevice extends Device {
  constructor (adapter, id, deviceDescription) {
  // ...
  this.disconnectTimer = this._startDisconnectTimer()
  }
}
```
How should I clear the timer when MyDevice object is removed/destroyed/deleted?

Right now I'm doing it by:
```javascript
class MyAdapter extends Adapter {
  removeThing (device) {
    if (device.disconnectTimer){
      clearTimeout(device.disconnectTimer)
      device.disconnectTimer = null
    }
    super.removeThing(device)
  }
}
```
because there is no callback in Device object that I could use.

It's a bit weird to use the MyAdapter object to release resources allocated by MyDevice object. I think Device object should be given a callback so that addon developers could use it to clear resources allocated during its lifetime.

**Comment by mrstegeman** [comment]
The primary reason is that the adapter is the only object directly owned/controlled by the add-on manager proxy, which is where everything flows from.

Here is an example for how to do this more cleanly:
```js
class MyAdapter extends Adapter {
  removeThing(device) {
    if (this.devices.hasOwnProperty(device.id)) {
      device.unload();
      this.handleDeviceRemoved(device);
    }

    return Promise.resolve(device);
  }
}

class MyDevice extends Device {
  unload() {
    if (this.disconnectTimer) {
      clearTimeout(this.disconnectTimer);
      this.disconnectTimer = null;
    }
  }
}
```
